migrate to api app routes
namehash/namehash-labs pull request #83
Opened 2024-05-04 08:08 UTC by notrab

This PR does the following:
* Replaces `npm` with `pnpm` so it's inline with all other projects
* Replaces the `/pages/api` routes with `app` route handlers

In a future PR we should move the contact-form submission to use a Server Action so we don't need to POST to the `/api/contact-form` route. We just use the code directly.

2024-05-06 13:22 UTC, lightwalker-eth requested changes
@notrab Some nice updates here. Reviewed and shared feedback. Thanks

2024-05-06 13:22 UTC, lightwalker-eth commented on middleware.ts
> +const allowedOrigins = ["https://acme.com", "https://my-app.org"];
@notrab Hmm, I assume this is something we should update / document with comments?

2024-05-06 13:22 UTC, lightwalker-eth commented on middleware.ts
> +export function middleware(request: NextRequest) {
@notrab Could we add more documentation into our code so it's more clear what we're working to achieve here? I see we're doing work here related to CORS, but the "why?" behind different decisions in the code here should be more documented so it's not such a black-box. Thanks

2024-05-06 13:30 UTC, notrab commented on middleware.ts
> +const allowedOrigins = ["https://acme.com", "https://my-app.org"];
@lightwalker-eth Yeah, we should add the sites we own that we want to allow `/api/` requests from. I posted in Slack, but it seems my message didn't go through.

2024-05-06 13:31 UTC, notrab commented on middleware.ts
> +export function middleware(request: NextRequest) {
Do we currently document the need for CORS anywhere? All I've done here is follow newer practices with Next.js than using the `nextcors` library.

Before we allowed any origin to make a request, but with middleware, we can make it a bit more difficult for bad actors so that only our sites/apps can access the `/api` endpoints.

https://nextjs.org/docs/app/building-your-application/routing/route-handlers#cors

2024-06-18 10:48 UTC, lightwalker-eth approved these changes
@notrab I somehow missed this PR! Thanks for your actions and updates here. Reviewed and approved 🚀

2024-06-18 18:50 UTC, eduramme approved these changes

2024-06-18 18:51 UTC, merged